@server=http://localhost:4004


### AvailableBoxCheck
# @name AvailableBoxCheck_GET
GET {{server}}/monitoring-service/AvailableBoxCheck



### AvailableBoxCheck
# @name AvailableBoxCheck_POST
POST {{server}}/monitoring-service/AvailableBoxCheck
Content-Type: application/json

{
  "ID": "92303712-158f-4618-950e-e994ab0d87f1",
  "DISBoxNumber": "DISBoxNumber-9230371",
  "PSAStatus": "PSAStatus-9230371",
  "PSABoxNumber": "PSABoxNumber-9230371",
  "DISProcessed": "DISProcessed-9230371",
  "Matched": false
}


### AvailableBoxCheck
# @name AvailableBoxCheck_PATCH
PATCH {{server}}/monitoring-service/AvailableBoxCheck/92303712-158f-4618-950e-e994ab0d87f1
Content-Type: application/json

{
  "ID": "92303712-158f-4618-950e-e994ab0d87f1",
  "DISBoxNumber": "DISBoxNumber-9230371",
  "PSAStatus": "PSAStatus-9230371",
  "PSABoxNumber": "PSABoxNumber-9230371",
  "DISProcessed": "DISProcessed-9230371",
  "Matched": false
}


### AvailableBoxCheck
# @name AvailableBoxCheck_DELETE
DELETE {{server}}/monitoring-service/AvailableBoxCheck/92303712-158f-4618-950e-e994ab0d87f1
Content-Type: application/json


### ShippedBolCheck
# @name ShippedBolCheck_GET
GET {{server}}/monitoring-service/ShippedBolCheck



### ShippedBolCheck
# @name ShippedBolCheck_POST
POST {{server}}/monitoring-service/ShippedBolCheck
Content-Type: application/json

{
  "ID": "23946099-8d69-49c9-bf29-b8fd03e17f39",
  "PSABolNo": "PSABolNo-239460",
  "PSATotalUnits": "PSATotalUnits-239460",
  "PSATotalVolume": "SATotalVolume-239460",
  "PSATotalBoxes": "PSATotalBoxes-239460",
  "DISBlading": "DISBlading-239460",
  "DISTotalUnits": "DISTotalUnits-239460",
  "DISTotalVolume": "ISTotalVolume-239460",
  "DISTotalBoxes": "DISTotalBoxes-239460",
  "MatchedUnits": true,
  "MatchedVolume": true,
  "MatchedBoxes": true,
  "Matched": true
}


### ShippedBolCheck
# @name ShippedBolCheck_PATCH
PATCH {{server}}/monitoring-service/ShippedBolCheck/23946099-8d69-49c9-bf29-b8fd03e17f39
Content-Type: application/json

{
  "ID": "23946099-8d69-49c9-bf29-b8fd03e17f39",
  "PSABolNo": "PSABolNo-239460",
  "PSATotalUnits": "PSATotalUnits-239460",
  "PSATotalVolume": "SATotalVolume-239460",
  "PSATotalBoxes": "PSATotalBoxes-239460",
  "DISBlading": "DISBlading-239460",
  "DISTotalUnits": "DISTotalUnits-239460",
  "DISTotalVolume": "ISTotalVolume-239460",
  "DISTotalBoxes": "DISTotalBoxes-239460",
  "MatchedUnits": true,
  "MatchedVolume": true,
  "MatchedBoxes": true,
  "Matched": true
}


### ShippedBolCheck
# @name ShippedBolCheck_DELETE
DELETE {{server}}/monitoring-service/ShippedBolCheck/23946099-8d69-49c9-bf29-b8fd03e17f39
Content-Type: application/json


### ShippedConsigneeBOLCheck
# @name ShippedConsigneeBOLCheck_GET
GET {{server}}/monitoring-service/ShippedConsigneeBOLCheck



### ShippedConsigneeBOLCheck
# @name ShippedConsigneeBOLCheck_POST
POST {{server}}/monitoring-service/ShippedConsigneeBOLCheck
Content-Type: application/json

{
  "ID": "17957908-abb3-4e58-a0e5-3b8ba37fd272",
  "PSABolNo": "PSABolNo-17957908",
  "PSAConsigneeNo": "ConsigneeNo-17957908",
  "DISBlading": "DISBlading-17957908",
  "DISCustomer": "DISCustomer-17957908",
  "Matched": true
}


### ShippedConsigneeBOLCheck
# @name ShippedConsigneeBOLCheck_PATCH
PATCH {{server}}/monitoring-service/ShippedConsigneeBOLCheck/17957908-abb3-4e58-a0e5-3b8ba37fd272
Content-Type: application/json

{
  "ID": "17957908-abb3-4e58-a0e5-3b8ba37fd272",
  "PSABolNo": "PSABolNo-17957908",
  "PSAConsigneeNo": "ConsigneeNo-17957908",
  "DISBlading": "DISBlading-17957908",
  "DISCustomer": "DISCustomer-17957908",
  "Matched": true
}


### ShippedConsigneeBOLCheck
# @name ShippedConsigneeBOLCheck_DELETE
DELETE {{server}}/monitoring-service/ShippedConsigneeBOLCheck/17957908-abb3-4e58-a0e5-3b8ba37fd272
Content-Type: application/json


### PartNumberBOLCheck
# @name PartNumberBOLCheck_GET
GET {{server}}/monitoring-service/PartNumberBOLCheck



### PartNumberBOLCheck
# @name PartNumberBOLCheck_POST
POST {{server}}/monitoring-service/PartNumberBOLCheck
Content-Type: application/json

{
  "ID": "14203797-64dc-4b8b-8a17-41c52aa1d8e3",
  "PSABolNo": "PSABolNo-14203797",
  "PSAPartNumber": "APartNumber-14203797",
  "DISBlading": "DISBlading-14203797",
  "DISPartNumber": "SPartNumber-14203797",
  "Matched": false
}


### PartNumberBOLCheck
# @name PartNumberBOLCheck_PATCH
PATCH {{server}}/monitoring-service/PartNumberBOLCheck/14203797-64dc-4b8b-8a17-41c52aa1d8e3
Content-Type: application/json

{
  "ID": "14203797-64dc-4b8b-8a17-41c52aa1d8e3",
  "PSABolNo": "PSABolNo-14203797",
  "PSAPartNumber": "APartNumber-14203797",
  "DISBlading": "DISBlading-14203797",
  "DISPartNumber": "SPartNumber-14203797",
  "Matched": false
}


### PartNumberBOLCheck
# @name PartNumberBOLCheck_DELETE
DELETE {{server}}/monitoring-service/PartNumberBOLCheck/14203797-64dc-4b8b-8a17-41c52aa1d8e3
Content-Type: application/json


### MaterialInformationCheck
# @name MaterialInformationCheck_GET
GET {{server}}/monitoring-service/MaterialInformationCheck



### MaterialInformationCheck
# @name MaterialInformationCheck_POST
POST {{server}}/monitoring-service/MaterialInformationCheck
Content-Type: application/json

{
  "ID": "1679832e-2b07-4541-aaf2-2cc705aa0ce0",
  "PSABoxNumber": "PSABoxNumber-1679832",
  "PSAMaterialDescription": "lDescription-1679832",
  "DISBoxNumber": "DISBoxNumber-1679832",
  "DISMaterialDesc": "MaterialDesc-1679832",
  "Matched": true
}


### MaterialInformationCheck
# @name MaterialInformationCheck_PATCH
PATCH {{server}}/monitoring-service/MaterialInformationCheck/1679832e-2b07-4541-aaf2-2cc705aa0ce0
Content-Type: application/json

{
  "ID": "1679832e-2b07-4541-aaf2-2cc705aa0ce0",
  "PSABoxNumber": "PSABoxNumber-1679832",
  "PSAMaterialDescription": "lDescription-1679832",
  "DISBoxNumber": "DISBoxNumber-1679832",
  "DISMaterialDesc": "MaterialDesc-1679832",
  "Matched": true
}


### MaterialInformationCheck
# @name MaterialInformationCheck_DELETE
DELETE {{server}}/monitoring-service/MaterialInformationCheck/1679832e-2b07-4541-aaf2-2cc705aa0ce0
Content-Type: application/json
